name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set timezone to Asia/Shanghai
        run: |
          echo "TZ=Asia/Shanghai" >> $GITHUB_ENV
          sudo timedatectl set-timezone Asia/Shanghai
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://goodlunatic.github.io/index.xml"
          max_post_count: 10
          template: "$newline- [$date $title]($url)"
          date_format: "yyyy-mm-dd HH:MM:ss"  # 使用所需的格式
